### PR TITLE
cope with multiple persons in one image

### PR DESCRIPTION
**Pull request by lindayuanyuan**
Thanks for your reply. I modified the code to save multiple headpose, gaze and estimate output files to cope with the multiple persons situiations. Please let me know if any questions. Thanks,
Yuanyuan

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks for this @lindayuanyuan, it looks good to me. This PR fixes #87.

@ahmed-alhindawi - the change is rather small - are you happy for it to be merged?

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by ahmed-alhindawi** [comment]
Very happy - thank you for asking (not really necessary!) and thank @lindayuanyuan  for contributing.

**Comment by lindayuanyuan** [comment]
My pleasure. Thanks for such a great tool. It helps my own research:)
Yuanyuan

Ahmed Al-Hindawi <notifications@github.com> 于2021年2月3日周三 上午9:59写道：

**Comment by Tobias-Fischer** [comment]
Thanks @lindayuanyuan for the contribution, and thanks @ahmed-alhindawi for the review :)

**Pull request merged**
